installCRDs: true
validatingWebhookConfigurationNamespaceSelector:
  matchExpressions:
    - key: control-plane
      operator: NotIn
      values:
        - 'true'
    - key: kubernetes.azure.com/managedby
      operator: NotIn
      values:
        - aks
